FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
		gcc \
        vim \
        telnet \
        net-tools \
        flex \
        bison

# 生成容器
# docker run -it --name myserver \
# -p 8080:80 \
# -v ~/docker/server/myServer:/home/server \
# --privileged=true \
# myserver bash

